### ISSUE TITLE
The theme adds a new point with 'highway=street_lamp' without making clear that the user maps a streetlamp

### ISSUE THREAD

**Issue by pietervdvn** [yopaseopor/osmlitmap#2]
When adding a new point, the user is presented with 'Add perception: <very bright to not bright>'. However, the OSM-database is told that there is a _street lamp_ there.

This is problematic, as users might be adding street lamps accidentally where there are none. **This is damaging to the openstreetmap project** as it erodes trust in data on other streetlamp data.

Can you verify that the [previously created points ](https://overpass-turbo.eu/s/1dDz) are actually streetlamps? If not, please remove them from the OSM.

Also see #1

**Comment by yopaseopor** [comment]
Fixed. Also I have seen 1 . Please stop saying using some non-standard process to complete information is damaging OSM and erode their trust. It is not true and it is not unfair.

**Comment by pietervdvn** [comment]
> Please stop saying using some non-standard process to complete information is damaging

This is not about how it is added, but what the result is. If wrong data ends up in OpenStreetMap (no matter how), this will erode trust in OpenStreetMap by data consumers.
